CREATE TABLE IF NOT EXISTS key (
    key_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) DEFAULT 'Key',
    content VARCHAR(250) NOT NULL UNIQUE,
    last_used MEDIUMINT
);

CREATE TABLE IF NOT EXISTS devicelist (
    devicelist_id INTEGER PRIMARY KEY AUTOINCREMENT,
    key_id INTEGER DEFAULT NULL,
    content TEXT DEFAULT NULL,
    last_updated MEDIUMINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS starred (
  starred_id INTEGER PRIMARY KEY AUTOINCREMENT,
  key_id INTEGER DEFAULT NULL,
  device_id TEXT DEFAULT NULL UNIQUE,
  last_updated MEDIUMINT DEFAULT NULL
);